### ISSUE TITLE
Create example app.

### ISSUE THREAD

**Issue by Trancever** [callstackincubator/bs-react-native-paper#36]
We should create example app which will use paper bindings. It's gonna help us in validating if our bindings works properly, if there are any errors and if we covered all possible components and apis (In v1 of bindings i saw at least one totally broken binding, with example app we could easily spot it and fix it).

I tried to do it but had troubles with dependencies, couldn't make metro working with generated files (I was trying to do it in same way as bs-react-native did their example app). @medson10 @grsabreu Would you mind taking look on it?

**Comment by medson10** [comment]
@Trancever yeah I can, until tomorrow I push a initial setup for this

**Comment by Trancever** [comment]
@medson10 Cool, looking forward to it :)

**Comment by medson10** [comment]
hi @Trancever, I'm sorry for my delay, but I'm busy this week at work. I'll send the pr with the example as soon as possible

**Comment by Trancever** [comment]
@medson10 Don't worry, it' ok :)
