### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by Trancever** [callstackincubator/bs-react-native-paper#71]
Since bindings are ready, we are good to go with releasing new version of `bs-react-native-paper` that supports new version of `react-native-paper`. There is only one thing left that we have to do. We have to merge `paper2.0` branch into master or (second option) rename master to `paper-v1` and rename `paper2.0` to master. Second option has small advantage, we would be able to make fixes on paper-v1 branch and release versions with fixes that supports `react-native-paper v1`. I am not sure if we need that so I am ok with both options. What do you think @medson10 ?

**Comment by medson10** [comment]
I liked the second option, it indeed is not need but will be useful if someone still using v1 and want to check how code was in this version. I think this is the best option for all module which a breaking change is released

**Comment by Trancever** [comment]
Version 5.0.0-alpha is released already! It's still alpha, cause we need to test it on real project and figure out bindings for withTheme HOC (@souhe I believe you are the right person to do it :p).

Btw, we can start promoting lib now :D @medson10 Send me your twitter handle and I'll mention you.

**Comment by medson10** [comment]
Nice, my twitter is @o_medson
