### ISSUE TITLE
Co-maintain with Callstack?

### ISSUE THREAD

**Issue by satya164** [callstackincubator/bs-react-native-paper#9]
Hey!

Really nice work with reason bindings for Paper. What do you think about moving the repo to the callstack org and co-maintain it with us? It'll ensure that it stays updated as new versions of Paper are released.

**Comment by fakenickels** [comment]
Hey, that's a really good idea @satya164. Let's do it

**Comment by guilhermedecampo** [comment]
Awesome!

**Comment by Trancever** [comment]
Hey, first of all sorry for not responding for so long, we had quite busy time working on paper v2.0. Are you still ok with that initiative of moving repo to callstack org and co-maintaining it with us? 
Btw, i saw that you started updating bindings to v2.0. What is the progress? Maybe i could help you with that?

**Comment by guilhermedecampo** [comment]
Yeah for sure. Let's do it. 
@medson10 can you lead that?

**Comment by medson10** [comment]
Sure

**Comment by medson10** [comment]
@Trancever for now we are updating as we need, adding new props and some other minor changes, and testing them in a real project, do you guys did some big change what can break the usage of some component?

**Comment by Trancever** [comment]
@medson10 You can find all the breaking changes in [Migration guide](https://github.com/callstack/react-native-paper/wiki/Migration-guide-for-2.0). In 2.0 many components are exposed as a static property of other component e.g. Dialog.Content, Dialog.Title so i am pretty sure old bindings will not work properly.

**Comment by medson10** [comment]
Got it, so we can use this as a roadmap to upgrade the bindings, @Trancever can you give me permission on callstackincubator organization so I can transfer the ownership and we continue this on there?

**Comment by Trancever** [comment]
Yeah, I'll ask someone who has permissions to do it, it might take up to few hours.

**Comment by Trancever** [comment]
@medson10 You should have permissions right now. Let me know if you need something else from our side.

**Comment by medson10** [comment]
@Trancever just transferred, thank you, now I just need the npm user of someone to give permission to publish the module

**Comment by Trancever** [comment]
@medson10 Cool! I can be that person. https://www.npmjs.com/~trensik
